### ISSUE TITLE
Project Briefing

### ISSUE THREAD

**Issue by ernestkorir** [ernestkorir/React-group-project#25]
In this Project:

Members: 2 
Project URL: https://github.com/ernestkorir/React-group-project/projects/1

Happy reviewing

**Comment by GedeonTS** [comment]
# INVALID REVIEW REQUEST

Hi @ernestkorir @yegonkimutai , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

Kindly make sure to include the Link to your project(Kanban board), not to your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AlphaNtihinduka** [comment]
# STATUS: APPROVED :green_circle: :clap: 
## Hi @ernestkorir  & @GedeonTS 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:
- Assigning the group assignments to both students. ✔️
- The cards with required categories are evenly assigned ✔️

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:
